### PR TITLE
Added Documentation and serialization support

### PR DESCRIPTION
**Pull request by epsilon-phase**
Merged your changes. 
Wrote some comments explaining what the various parts of the plugin system do.

### CODE REVIEW

**Comment by csm10495** [comment]
Few things:
- This is pretty cool, though I need a couple things done:
  - Why do the plugins need to be saved every second? Seems wasteful / possibly a bit IO intensive.
  - Also clear up the warnings, some imports were added that were already there, etc.
  - Finally please follow the XML style for commenting functions (to keep it in similar style to the existing code-base).
  - We also need documentation for how the user can make Plugins, its not really clear from the coding perspective. 
  - Finally, please remove test classes from the repo as I don't want to add more than needed to make it work.
  - All classes should also be named reasonably, as you know (though I don't think that is an issue for your production stuff)

**Comment by epsilon-phase** [comment]
So you don't think including an example plugin with it would be a reasonable introduction to the way the plugin system works?

**Comment by csm10495** [comment]
It is but I'd rather it be seperate from the main repo.

On Tuesday, March 10, 2015, Alexander White notifications@github.com
wrote:

> So you don't think including an example plugin with it would be a
> reasonable introduction to the way the plugin system works?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/csm10495/cDashboard/pull/12#issuecomment-78162093.

## 
- Charlie Scott Machalow

**Comment by epsilon-phase** [comment]
Okay, I'll see if I can add this as an optional submodule, is that alright?

**Comment by csm10495** [comment]
Something that's not automatically downloaded with the main repo

On Tuesday, March 10, 2015, Alexander White notifications@github.com
wrote:

> Okay, I'll see if I can add this as an optional submodule, is that alright?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/csm10495/cDashboard/pull/12#issuecomment-78165027.

## 
- Charlie Scott Machalow

**Comment by epsilon-phase** [comment]
That's what's happened. Now the cDashboard repo is a submodule of it, which seems wrong, but also seems to work well enough for me to forgive that.

**Comment by csm10495** [comment]
CDashboard should not be a sub module of it, it should be the other way
around and a seperate repo. If I download the source code zip, it should
not be included. (Which it is in this)

On Tuesday, March 10, 2015, Alexander White notifications@github.com
wrote:

> That's what's happened. Now the cDashboard repo is a submodule of it,
> which seems wrong, but also seems to work well enough.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/csm10495/cDashboard/pull/12#issuecomment-78172113.

## 
- Charlie Scott Machalow

**Comment by epsilon-phase** [comment]
Oh, it is separated now, you download the cDashboardPluginTest repo and then run git submodule update or init, then it should be good.

**Comment by csm10495** [comment]
oh crap, I see what you mean now, sorry i was downloading via zip in GitHub instead of cloning, weird.

EDIT: I messed up, see below.

**Comment by csm10495** [comment]
Why does it still come up the way it does in GitHub?

**Comment by csm10495** [comment]
Nope, forget that, lol I was looking at the old commit in GitHub and then cloning the new one lol. This was is much better to me, the minor code fixes and we will be golden.

**Pull request closed without merging**
