### PR TITLE
It is done, rudimentary plugin support has been added.

### PR DESCRIPTION
**Pull request by epsilon-phase**
I was surprised how simple this actually was to do, it does mean that a lot of things will have to be replicated, but it does seem to work now, at least, sufficiently well to consider pushing.
MEF is nice, btw.

### CODE REVIEW

**Comment by csm10495** [comment]
Do me a couple of favors and submit a new pull request after doing the following:
- Comment a bit more, I understand how it works but, some more comments wouldn't hurt
- Have a way for a user to add a dll to the application without having to drag files to certain folders
  - Have the dlls be in the normal settings location folder
- Think about persistence, is there anyway to have a plugin persist throughout application restarts, similar to cForms?

Otherwise this is a great start!

**Comment by epsilon-phase** [comment]
Would you mind if I just exported the cForm class? It seems this sort of thing should be supported.

**Comment by csm10495** [comment]
What do you mean by exporting cForm?

**Comment by epsilon-phase** [comment]
Well, actually, I don't believe that it should need to be modified at all, I might just be able to specify that the plugin gets a cForm.

**Comment by csm10495** [comment]
I like that idea. Then size, location could be tracked and saved automatically. Then you only need to come up with some type of data API for data persistence.

**Comment by epsilon-phase** [comment]
I've decided, based on flexibility, to just have the plugin specify a system for saving their relevant data and loading it up, as it seems that your widgets are rather diverse in their methods for handling this as well.

**Pull request closed without merging**
